### ISSUE TITLE
Arch Linux proot-distro

### ISSUE THREAD

**Issue by shim80** [WMCB-Tech/termux-wayland#34]
I use proot-distro with Arch Linux.
I tried to make it work with XWayland, but when I try to launch with
`export XDG_RUNTIME_DIR=$TMPDIR

Xwayland :0 1> /dev/null &

env DISPLAY=:0 gnome-session`
I got:
`[1] 22159
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
glamor: No eglstream capable devices found
could not connect to wayland server
(EE)
Fatal server error:
(EE) Couldn't add screen
(EE)
dbus[22165]: Unable to set up transient service directory: XDG_RUNTIME_DIR "/tmp" can be written by others (mode 041777)
Unable to init server: Could not connect: Connection refused

(gnome-session-check-accelerated:22170): Gtk-WARNING **: 11:22:51.712: cannot open display: :0
Unable to init server: Could not connect: Connection refused

(gnome-session-check-accelerated:22171): Gtk-WARNING **: 11:22:51.999: cannot open display: :0
gnome-session-binary[22160]: WARNING: software acceleration check failed: Child process exited with code 1
Unable to init server: Could not connect: Connection refused

** (gnome-session-failed:22172): WARNING **: 11:22:52.206: Cannot open display:
[1]+  Exit 1                  Xwayland :0 > /dev/null
Terminated`

**Comment by suhan-paradkar** [comment]
Did you launch proot-distro with shared tmp??
Like this??
```bash
proot-distro login archlinux --shared-tmp
```

**Comment by shim80** [comment]
Just tried, now it's showing :
`
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
glamor: No eglstream capable devices found
missing XDG-WM-Base protocol
(EE)
Fatal server error:
(EE) Couldn't add screen
(EE)

(gnome-session-check-accelerated:29482): Gdk-WARNING **: 11:39:27.990: The Wayland compositor does not provide any supported shell interface, not using Wayland display
Unable to init server: Could not connect: Connection refused

(gnome-session-check-accelerated:29482): Gtk-WARNING **: 11:39:28.016: cannot open display: :0

(gnome-session-check-accelerated:29487): Gdk-WARNING **: 11:39:29.329: The Wayland compositor does not provide any supported shell interface, not using Wayland display
Unable to init server: Could not connect: Connection refused

(gnome-session-check-accelerated:29487): Gtk-WARNING **: 11:39:29.371: cannot open display: :0
gnome-session-binary[29472]: WARNING: software acceleration check failed: Child process exited with code 1
Unable to init server: Could not connect: Connection refused

** (gnome-session-failed:29492): WARNING **: 11:39:29.624: Cannot open display:
[1]+  Exit 1                  Xwayland :0 > /dev/null
Terminated
`

**Comment by suhan-paradkar** [comment]
Can you try that again after installing weston

**Comment by shim80** [comment]
Just tried. Same error.

**Comment by shim80** [comment]
What do you mean? I always launch Termux Wayland app before.
It's actually work with Termux Desktop (openbox), but not when I start from proot-distro

**Comment by suhan-paradkar** [comment]
Looks like it has a few problems that needs resolution... But it's mostly a problem with the packages...
I could run Xwayland smoothly in alpine tho using the `--shared-tmp` option

**Comment by suhan-paradkar** [comment]
Looks like proot too has issues... Check termux/proot/#131

**Comment by RalfWerner** [comment]
>What do you mean? I always launch Termux Wayland app before.

Also `Xwayland` is to start in Termux before `* login *` and with the `--shared-tmp` argument I've check here the XClient `xterm` (_arch-xterm_ process 7 and 8 in the shot).
So far, in addition to Termux, I also used _Debian_ and _Ubuntu_ as distros (sufficient for me and rarely used). For check I also installed _archlinux_ and `pacman -s xterm` on my SM-P610. There I was able to start XClients next to Termux also from two distros. Due to difficult finger control, I do not use Window Manager or turn it on/off with _Termux_-EK (Extra-Keys left above Nav-Bar in shot)
![grafik](https://user-images.githubusercontent.com/45426380/129751639-a9c529fe-3df2-4db3-be1e-7e8bbc762254.png)
### What to see here and what not:
The tablet is in _landscape_ position and the Apps _Termux_ (transparent) and _T:Wayland_ can be seen _in Picture_ over the start screen (with widget table). I use a floating transparent OS-KB (bottom right) and _both EK_ can be used. To do this, the last two choices must be _switched off_ in [Preferences](https://github.com/suhan-paradkar/termux-wayland/discussions/18#discussioncomment-1094511). This is the _**only 1)** possibility_ to do that on the device.
By Widget-tap (supplemented by _arch*_) I started 9 processes, displayed in the Drawer (EK or drag) and their logs in Termux. The two _arch-xterm_ windows are down-left and center ("Main options" with CTR+sweep) from _T:Wayland_, top right is (N)_edit-ubuntu_. And the rest is filled with my two check XClients (`*.c`) whose OS (Termux/Ubuntu) is unclear, as make on both works but in Termux with better performance.

**1)** All other attempts to use the EK of Wayland (always at the bottom) failing, as they are covered both in the Split like Full Screen by the Nav-Bar and at _non-floating_ OS-KB half of Wayland Picture/Window is overlaps. In the original _T:X11_ were the EK at the top, which prevents this effect and also problems that occur by proximity to the Nav-Bar.

**Comment by suhan-paradkar** [comment]
Well.. here's the solution... Update `proot` ...
It has been fixed not to throw errors while running DE's like KDE in proot-distro... also.. note that GNOME requires systemd to begin with to manage sessions.. so.. I don't think that's gonna work at all...

**Comment by suhan-paradkar** [comment]
Closing since it is a proot-distro/proot issue
